---

- name: Triple VPN | Middle Node
  hosts: all
  become: yes
  roles:
  - common
  - role: openvpn
    vars:
      os_req: 'Debian'
      ram_req: '450'
      cpu_req: 1
      hdd_req: "5120"
      tun_check: true
      nat_tun: tun3
      firewall_disable_ufw: true
      openvpn_install: true
      middlenode: true
      dh_param: 2048
      client_profile: "{{ profile_path }}/vpn_triple_hop2.conf"
      nextsrv_client_profile: "{{ shared_folder_path }}/vpn_triple_hop3.conf"
      openvpn_udp_port: 1194
      openvpn_udp_net: 10.9.0
