---

- name: Single VPN
  hosts: all
  become: yes
  roles:
  - common
  - role: openvpn
    vars:
      os_req: 'Debian'
      ram_req: '450'
      cpu_req: 1
      hdd_req: "5120"
      tun_check: true
      clientname: single
      profile_path: ~/openvpn_profiles
      nat_tun: "{{ ansible_default_ipv4.interface }}"
      firewall_disable_ufw: true
      openvpn_install: true
      standalone: yes
      torrents_block: no
      bind_forward_only: true
      bind_forwarders: [ 8.8.8.8 , 8.8.4.4 ]
      is_obfsproxy: false
      duplicate: true
      privoxy_install: true
      obfs_type: obfs3
      obfs_port: 21
      obfs_local_port: 1025
      dh_param: 2048
      openvpn_udp_port: 443
      openvpn_tcp_port: 443
      openvpn_udp_net: 10.11.0
      openvpn_tcp_net: 10.12.0
